<h1>F1 Data Analysis - Potfolio project</h1><br>
<p>In this project, I am going to show all my skills that I have gained through Codeacdemy Intoduction to Data Science/ML fundamentals course. I hope that</p>

<h1>This should be written and explained what is going on</h1><br>

<h3>What we are trying to find out from data gather over 70 years of F1 history</h3><br>

In [22]:
import numpy as np
import pandas as pa
import seaborn as sea

circuits = pa.read_csv("C:/Users/nikol/CS513JupiterNotebook/F1DataAnlysis/F1 Data Analytics Project/circuits.csv")
circuits = pa.read_csv("C:/Users/nikol/CS513JupiterNotebook/F1DataAnlysis/F1 Data Analytics Project/circuits.csv")
circuits = pa.read_csv("C:/Users/nikol/CS513JupiterNotebook/F1DataAnlysis/F1 Data Analytics Project/circuits.csv")
circuits = pa.read_csv("C:/Users/nikol/CS513JupiterNotebook/F1DataAnlysis/F1 Data Analytics Project/circuits.csv")
circuits = pa.read_csv("C:/Users/nikol/CS513JupiterNotebook/F1DataAnlysis/F1 Data Analytics Project/circuits.csv")
circuits = pa.read_csv("C:/Users/nikol/CS513JupiterNotebook/F1DataAnlysis/F1 Data Analytics Project/circuits.csv")
circuits = pa.read_csv("C:/Users/nikol/CS513JupiterNotebook/F1DataAnlysis/F1 Data Analytics Project/circuits.csv")
circuits = pa.read_csv("C:/Users/nikol/CS513JupiterNotebook/F1DataAnlysis/F1 Data Analytics Project/circuits.csv")
circuits = pa.read_csv("C:/Users/nikol/CS513JupiterNotebook/F1DataAnlysis/F1 Data Analytics Project/circuits.csv")


print(circuits)

circuits.head()

    circuitId   circuitRef                                  name  \
0           1  albert_park        Albert Park Grand Prix Circuit
1           2       sepang          Sepang International Circuit
2           3      bahrain         Bahrain International Circuit
3           4    catalunya        Circuit de Barcelona-Catalunya
4           5     istanbul                         Istanbul Park
..        ...          ...                                   ...
72         75     portimao    Autódromo Internacional do Algarve
73         76      mugello  Autodromo Internazionale del Mugello
74         77       jeddah               Jeddah Corniche Circuit
75         78       losail          Losail International Circuit
76         79        miami         Miami International Autodrome

        location       country       lat        lng  alt  \
0      Melbourne     Australia -37.84970  144.96800   10
1   Kuala Lumpur      Malaysia   2.76083  101.73800   18
2         Sakhir       Bahrain  26.03250   50.51060    7
3       Montmeló         Spain  41.57000    2.26111  109
4       Istanbul        Turkey  40.95170   29.40500  130
..           ...           ...       ...        ...  ...
72      Portimão      Portugal  37.22700   -8.62670  108
73       Mugello         Italy  43.99750   11.37190  255
74        Jeddah  Saudi Arabia  21.63190   39.10440   15
75     Al Daayen         Qatar  25.49000   51.45420   12
76         Miami           USA  25.95810  -80.23890    0

                                                  url
0   http://en.wikipedia.org/wiki/Melbourne_Grand_P...
1   http://en.wikipedia.org/wiki/Sepang_Internatio...
2   http://en.wikipedia.org/wiki/Bahrain_Internati...
3   http://en.wikipedia.org/wiki/Circuit_de_Barcel...
4          http://en.wikipedia.org/wiki/Istanbul_Park
..                                                ...
72  http://en.wikipedia.org/wiki/Algarve_Internati...
73       http://en.wikipedia.org/wiki/Mugello_Circuit
74  http://en.wikipedia.org/wiki/Jeddah_Street_Cir...
75  http://en.wikipedia.org/wiki/Losail_Internatio...
76  http://en.wikipedia.org/wiki/Miami_Internation...

[77 rows x 9 columns]

,circuitId,circuitRef,name,location,country,lat,lng,alt,url
0,1,albert_park,Albert Park Grand Prix Circuit,Melbourne,Australia,-37.84970,144.96800,10,http://en.wikipedia.org/wiki/Melbourne_Grand_P...
1,2,sepang,Sepang International Circuit,Kuala Lumpur,Malaysia,2.76083,101.73800,18,http://en.wikipedia.org/wiki/Sepang_Internatio...
2,3,bahrain,Bahrain International Circuit,Sakhir,Bahrain,26.03250,50.51060,7,http://en.wikipedia.org/wiki/Bahrain_Internati...
3,4,catalunya,Circuit de Barcelona-Catalunya,Montmeló,Spain,41.57000,2.26111,109,http://en.wikipedia.org/wiki/Circuit_de_Barcel...
4,5,istanbul,Istanbul Park,Istanbul,Turkey,40.95170,29.40500,130,http://en.wikipedia.org/wiki/Istanbul_Park